### ISSUE TITLE
Wrong prefix path on M1 via homebrew

### ISSUE THREAD

**Issue by chrisb86** [fabianishere/pam_reattach#3] opened 2021-01-15 14:09 UTC
I'm using an M1 MBA and installed pam_reattach via brew.

The brew prefix on M1 macs is /opt/homebrew. That's where the formula is installed.

But that's not the path where PAM looks for the modules.

Would it be possible to hardcode /usr/local as prefix anywhere or to tell PAM too look in /op/homebrew too?

I installed it manuallly now and it works like a charm. Thank you very much!

**Comment by fabianishere** [comment] 2021-01-15 22:38
Hi Chris,

Thank you for reporting this issue. 

However, I am not sure how to proceed. I don't think the PAM search path can be changed. The only solution for now would be to specify the full path to the module in the `/etc/pam.d/*` files.

**Comment by chrisb86** [comment] 2021-01-16 08:55
Okay, this works. I should have read the manpage for pam. I created a PR for adding a note in the README.

**Comment by fabianishere** [comment] 2021-01-16 11:10
I have merged #4, so I think we can close the issue for now.

**Closed as completed by fabianishere** 2021-01-16 11:10 UTC
Labels: bug

**Comment by cormacrelf** [comment] 2021-03-04 09:08
I used the method recommended in the readme for Homebrew installations on M1 (`auth optional /opt/homebrew/lib/pam/pam_reattach.so`) and it worked only in Terminal.app, not via Alacritty/tmux. The latter complained about `sudo: unable to initialize PAM: No such file or directory`. I killed tmux server, etc etc. Nope. Eventually just installed from source into /usr/local and removed the absolute path, now it works in both.

**Comment by fabianishere** [comment] 2021-03-04 09:34
@cormacrelf Thanks for reporting this. I cannot reproduce it myself on my Intel Macbook, but I think your workaround is suitable. If you prefer to install it via Homebrew, you could also create a symlink to the file at `/usr/lib/pam/pam_reattach.so`.

**Comment by cormacrelf** [comment] 2021-03-04 11:02
I figured it out, actually. It's the same issue that probably every single other M1 installation problem is caused by. I could just skip straight to the solutions but eh. May as well write it out. The upshot is that you **really need a universal binary on M1** and the homebrew script should attempt to set this where possible.

I found that the built from source install had in fact stopped working in Terminal.app, and eventually realised that **`sudo` is a universal binary and that error message really means "we couldn't find an appropriate arch file at that path"**. PAM loads .so files into a running program, so it has to match the arch of that program. Also, processes inherit the default executable architecture choice of their parent process, which can be overridden for a process and its subprocesses if you invoke it with `arch -arm64`.

Here's the difference between the two setups I had going:

```
Apple Terminal (arm64, default arm64)
--- starts shell (arm64 only, default arm64)
    --- starts sudo (universal => arm64, default arm64)
        --- attempts to load arm64 binaries into arm64 program

Alacritty (Rosetta, default Rosetta)
--- starts tmux server (arm64 only, default Rosetta)
    --- starts shell (arm64 only, default Rosetta)
        --- starts sudo (universal => Rosetta, default Rosetta)
            --- attempts to load x86_64 binaries into Rosetta program
```

Homebrew default is to install only the current arch. Hence works in Apple Terminal, as sudo runs as arm64, but fails in tmux, which has inherited Alacritty's default universal executable choice of Rosetta. Also, when building source, the latest CMake release (3.19.x) doesn't yet incorporate [this pr](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5589), so the `cmake` command will configure arm64 targets when run as arm64, and x86_64 targets when it is running under Rosetta. So it is all very annoying.

The solution is:

- Build as universal binary, as described in the README, so any kind of sudo can load it. **Universal should be the default on homebrew where possible**. You don't know where else you're going to need sudo, which can and will run in Rosetta mode, to work.
- If using a Rosetta-emulated terminal app, make sure you launch your tmux server from within `arch -arm64` to prevent more issues like this, esp building things with cmake.

Here's my Alacritty tmux init configuration:

```yaml
shell:
  program: /usr/bin/arch
  args:
    - '-arm64'    # ensure default arch for universal executables is arm64, despite alacritty being x86_64
    - '/bin/sh'
    - '--login'   # run as login shell to load a basic PATH from ~/.profile so homebrewed tmux is in there
    - '-c'
    - 'tmux attach -t TMUX || tmux new -s TMUX'
```

**Comment by fabianishere** [comment] 2021-03-04 11:20
@cormacrelf Very interesting! Let's see whether I can make the PAM module universal.

**Comment by cormacrelf** [comment] 2021-03-04 12:42
If you're doing it from the Homebrew formula, which you have to I think because CMake doesn't currently break out of Rosetta to discover it's running on M1, then it's something like `args << "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" if Hardware::CPU.arm?`, but atm this is not actually producing universal binaries. It really should though. All the clang invocations in the logs have `-arch arm64 -arch x86_64` etc.

**Comment by cormacrelf** [comment] 2021-03-04 12:53
Ah, you also need `ENV.permit_arch_flags` otherwise homebrew's clang shim will throw them out.

```diff
 def install
     args = std_cmake_args
     args << "-DENABLE_CLI=ON" if build.with? "cli"
+    args << "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" if Hardware::CPU.arm?
+    ENV.permit_arch_flags
     # ...
 end
```

**Comment by fabianishere** [comment] 2021-03-04 19:05
@cormacrelf What does it currently produce if there are not universal binaries? Does it just build both architectures separately?

**Comment by cormacrelf** [comment] 2021-03-04 19:40
With `brew install fabianishere/personal/pam_reattach` as it is now, if you have an /opt/homebrew arm64 Homebrew, it builds an arm64 .so. If you also install brew into /usr/local and run `arch -x86_64 /usr/local/bin/brew install ...` it builds an x86_64 .so into /usr/local/lib/pam. So when built with homebrew it just builds the single arch homebrew wants it to build, which is is a static property of the homebrew installation.

You can of course tell the difference by running `file /opt/homebrew/lib/pam/pam_reattach.so`. For an arm64 only binary it will show `Mach-O 64-bit bundle arm64`. For a universal binary, file will show 3 lines, most notably `Mach-O universal binary with 2 architectures`.

I realise I didn't quite make it super clear: that Formula diff is literally it. Done. Just push that to your tap repo. With those lines it builds universal on M1, because the second line allows it to override the Homebrew installation.

**Comment by fabianishere** [comment] 2021-03-04 19:53
That makes sense! Thank you for the information. Will update the Homebrew formula

**Comment by fabianishere** [comment] 2021-03-05 09:28
Hi @cormacrelf, I have updated the formula in my Homebrew repository. I can't test it myself, since Homebrew doesn't support cross-compiling to ARM64 on Intel machines, however I have verified it to work when building it myself from source. Let me know if it works for you!

**Comment by jessejoe** [comment] 2022-09-29 04:27
Just want to add a suggestion to modify the help text for the homebrew forumula caveats which are show post-install. They currently say:
```
==> Caveats
Make sure you add the module to your targeted service in /etc/pam.d/ before
the module you want put in the per-session bootstrap namespace:

  auth  optional    pam_reattach.so
  auth  sufficient  pam_tid.so
  ...

See https://github.com/fabianishere/pam_reattach
```

I followed those on my M1 Mac and locked myself out of sudo. I think it would be helpful to update the text with a disclaimer about M1.

**Comment by fabianishere** [comment] 2022-09-30 09:11
@jessejoe You are probably referring to the Homebrew formula in my personal Homebrew repository? That formula is not maintained anymore now that the formula is available in the general Homebrew repository.

**Comment by jessejoe** [comment] 2022-10-07 13:24
@fabianishere ah, what actually happened was I specified the official package, but had previously downloaded the one from your repo, so it used that cached one instead:
```
$ brew reinstall pam_reattach
==> Downloading https://github.com/fabianishere/pam_reattach/archive/v1.2.tar.gz
Already downloaded: ~/Library/Caches/Homebrew/downloads/bb6ad598816f7295b3479f98ffcfafae27308ea1aefd086c995e3a3ec71c897a--pam_reattach-1.2.tar.gz
==> Reinstalling fabianishere/personal/pam_reattach
==> cmake . -DCMAKE_OSX_ARCHITECTURES=arm64;x86_64
==> make install
==> Caveats
Make sure you add the module to your targeted service in /etc/pam.d/ before
the module you want put in the per-session bootstrap namespace:

  auth  optional    pam_reattach.so
  auth  sufficient  pam_tid.so
  ...

See https://github.com/fabianishere/pam_reattach
```

The official one doesn't seem to have any `Caveats` post-install. I wonder if it would make sense to at least amend the output in your personal package since so many links on the internet suggest installing that one and it's still available in Homebrew?

**Comment by fabianishere** [comment] 2022-10-10 08:34
@jessejoe I agree with your suggestion. I have now updated the package in my personal repository to refer to the official package in the Homebrew core repository and changed the `Caveats` to refer to the README.

**Comment by shawnz** [comment] 2025-03-10 18:53
Is this supposed to be fixed with the package in the Homebrew core repository? I am installing from there and still getting the `sudo: unable to initialize PAM: No such file or directory` message, and `file /opt/homebrew/lib/pam/pam_reattach.so` shows `Mach-O 64-bit bundle arm64`. Was there a regression?
